#ifndef COMMUNICATIONPLUGIN_GLOBAL_H
#define COMMUNICATIONPLUGIN_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef COMMUNICATIONPLUGIN_LIB
# define COMMUNICATIONPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define COMMUNICATIONPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMUNICATIONPLUGIN_GLOBAL_H
